

```{r, message=FALSE}
library(ggplot2)
library(ggpubr)
```

Read in data from both analyses for comparison:

```{r, message = FALSE}
irish_nsl_data <- read.table(file = "data/selection_analyses/out_irish_hetremoved_raresnpsremoved_with_nsl_score_abs_top_score_per_gene.txt",
                       header = FALSE)
irish_nsl_data <- irish_nsl_data[, c(5,6)]
colnames(irish_nsl_data) <- c("locus",
                              "nsl_score")

british_nsl_data <- read.table(file = "data/selection_analyses/british_nsl_scores.txt",
                               header = FALSE)
colnames(british_nsl_data) <- c("locus",
                                "nsl_score")
irish_nsl_data$brit_nsl_score <- british_nsl_data[match(irish_nsl_data$locus,
                       british_nsl_data$locus), ]$nsl_score
irish_nsl_data$brit_nsl_score <- gsub(pattern = ",",
     replacement = ".",
     irish_nsl_data$brit_nsl_score)

irish_nsl_data$brit_nsl_score <- as.numeric(as.character(unlist(irish_nsl_data$brit_nsl_score)))

ggplot(data = irish_nsl_data,
       aes(x = nsl_score,
          y = brit_nsl_score)) +
  geom_point()
```

Read in the immune genes:

```{r, message = FALSE}
immune_genes <- scan(file = "data/gene_lists/barribeau_2015_gene_symbols.txt",
                           as.character())

## Subset:
irish_nsl_immune <- subset(x = irish_nsl_data,
                           locus %in% immune_genes)

ggplot(data = irish_nsl_immune,
       aes(x = nsl_score,
          y = brit_nsl_score)) +
  geom_point(alpha = 0) +
  geom_point(data = irish_nsl_immune,
             colour = "black",
             alpha = 0.5) +
  geom_point(data = subset(irish_nsl_immune,
                           nsl_score >= 2 &
                           brit_nsl_score >= 2),
             aes(colour = "blue")) +
  geom_smooth(method = "lm",
              colour = "black",
              linetype = "dashed",
              alpha = 0.5) +
  geom_vline(xintercept = 2,
             linetype = "dashed",
             alpha = 0.5) +
  geom_hline(yintercept = 2,
             linetype = "dashed",
             alpha = 0.5) +
  xlab(label = "|nSL| score - Irish population") +
  ylab(label = "|nSL| score - British population") +
  #geom_segment(aes(x = 0 , y = 2, xend = 2, yend = 2)) +
  #geom_segment(aes(x = 2 , y = 0, xend = 2, yend = 2)) +
  #geom_segment(aes(x = 0 , y = 2.75, xend = 2.87, yend = 2.75)) +
  #geom_segment(aes(x = 2.87 , y = 0, xend = 2.87, yend = 2.75)) +
  stat_cor() +
  theme_bw() +
  theme(legend.position = "none",
        axis.title = element_text(face = "bold",
                                  size = 12))

## Save figure:
ggsave(filename = "results/island_nsl_comparison.png",
       height = 5,
       width = 5)

## There are 34 genes both with patterns of significant positive selection:
## Construct a contingency table:
conserved_immune <- nrow(subset(irish_nsl_immune,
                                nsl_score >= 2 &
                                brit_nsl_score >= 2))

conserved_total <- nrow(subset(irish_nsl_data,
                               nsl_score >= 2 &
                               brit_nsl_score >= 2))

conserved_non_immune <- conserved_total - conserved_immune

selected_genes <- c(conserved_immune, conserved_non_immune)

## Non-selected genes:
nonselected_immune_genes <- nrow(irish_nsl_immune) - conserved_immune

nonselected_non_immune <- nrow(irish_nsl_data) - 
                               nonselected_immune_genes - 
                               conserved_immune - 
                               conserved_non_immune 
conserved_immune <- nrow(irish_nsl_data)
conserved_total <- nrow(subset(irish_nsl_data,
                               nsl_score >= 2 &
                               brit_nsl_score >= 2))

conserved_non_immune <- conserved_total - conserved_immune

selected_genes <- c(conserved_immune, conserved_non_immune)

nonselected_immune_genes <- nrow(irish_nsl_immune) - conserved_immune

nonselected_non_immune <- nrow(irish_nsl_data) - 
                                nonselected_immune_genes - 
                                conserved_immune - 
                                conserved_non_immune
non_selected_genes <- c(nonselected_immune_genes,
                        nonselected_non_immune)

## Create a contingency table:
contingency_table <- rbind(selected_genes,
                           non_selected_genes)
contingency_chi <- chisq.test(contingency_table)
contingency_chi
```
