#!/usr/bin/env R
##############################################################################
##
##  Author: Joe Colgan (joscolgan)                Program: median_counter.R
##
## Date: 29/05/22
##
## Purpose:
## The purpose of this script is to take the following as input from the 
## command line:
## 1) Input file containing physical position of site (chrom, base) and read depth
## 2) Name to assign to output file.
## This script is a modification of a script generated by Colgan et al. (2022):  
## (https://doi.org/10.1093/molbev/msab366)
##############################################################################

## Take input from the command line:
args <- commandArgs(TRUE)
input <- args[1]            # Assign first argument as input
output <- args[2]           # Assign second argument as output

## Print message to console:
message(paste("will output to", output))

## The purpose of this script is to take in a text file containing three columns:
##      - Chromosome - base position - read depth
##        B01              1       6
##              ..              ..      ..
## and calculate the median for the third column "read depth"

# Define function 'median_counts':  
median_counts<-function() {
        data<-read.table(input, header=FALSE) ## Read in input from command line
        data.colMedians <- median(as.matrix(data[,3]))
        write.table(data.colMedians,
                    file = output,
                    row.names = FALSE,
                    col.names = FALSE,
                    quote = FALSE,
                    sep = "\t")
}

## Call the function
median_counts()
