#!/usr/bin/env Rscript
##########################################################################################
##
## Author: Joe Colgan                           Program: run_filter_windows.R
##
## Date: 20-04-2022
##
## Purpose:
## The purpose of the script was to take a tab-delimited text file generated by
## seqtk 'comp' containing information on the base composition of sequences of 100kb windows,
## calculate the proportion of ambiguous (N) bases and to remove windows where the 
## the proportion of N bases was equal to or more than 10%. 
## The script outputs a tab-delimited text file containing filtered windows. 
##
##########################################################################################

## Take arguments from the command line:
args = commandArgs(trailingOnly=TRUE)

input  <- args[1]
print(input)

output <- args[2]
print(output)

## Read in input:
data <- read.table(file = input,
                   header = FALSE)

## Calculate the percentage of the window with N bases:
data$V14 <- data$V9 / data$V2

## Subset windows where 10% or less of the window consists of N bases:
filtered_data <- subset(x = data,
                        V14 <= 0.1)

## Write file to output:
write.table(x = filtered_data,
            file = output,
            row.names = FALSE,
            col.names = FALSE,
            quote = FALSE,
            sep = "\t")
